# version: "3"
# services:
#   nginx:
#     container_name: nginx
#     build: ./docker/nginx
#     links:
#       - php
#     ports: 
#       - "8080:80"
#     networks:
#       - internal
#     volumes: 
#       - ./src:/var/www/html/
#     working_dir: /var/www/html
#   php:
#     container_name: php
#     image: php:fpm-alpine
#     networks:
#       - internal
#     volumes: 
#       - ./src:/var/www/html/
#     working_dir: /var/www/html
# networks:
#   internal:
#     driver: bridge

version: '3.4'
services:
    mysql:
        image: mysql:8.0
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: laravel
    backend:
        tty: true
        stdin_open: true
        command: bash
        build: ./docker
        links:
            - mysql
        ports:
            - 8000:8000
        environment:
            APP_DEBUG: 'true'
            XDEBUG_MODE: coverage
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin
        volumes:
            - ./Laravel:/www:cached
            - ./docker-dev/web/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./docker/supervisor/:/etc/supervisor.d/
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
        - 8081:80
        links:
        - mysql
        environment:
        - PMA_ARBITRARY=1
    frontend:
        image: node:lts
        entrypoint: /bin/bash
        ports:
        - 8080:8080
        volumes:
        - ./Vuejs:/www:cached
        tty: true
volumes:
    composer_caches:
    mysql-data:
networks:
  app-network:
    driver: bridge