version: "3"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    links:
      - php
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes: 
      - ./src:/var/www/html/
    working_dir: /var/www/html
  php:
    container_name: php
    image: php:fpm-alpine
    networks:
      - internal
    volumes: 
      - ./src:/var/www/html/
    working_dir: /var/www/html
networks:
  internal:
    driver: bridge